name: Publish Snapshot
on:
  push:
    branches:
      - main
      - dev-snapshot**
      - v*.*.**
    paths:
      - '**src/main/kotlin/**.kt'
      - '**.kts'
      - '**src/main/java/**.java'

env:
  IS_CI: true
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SIMBOT_IS_SNAPSHOT: true
  SIMBOT_SNAPSHOT_ONLY: true
  GRADLE_OPTS: "-Xmx8g -Xms2g -Dfile.encoding=UTF-8"

jobs:
  publish-snapshot:
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v3

      # setup Java
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      # setup Gradle
      - name: Gradle publish snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
          arguments: clean test publishToSonatype closeAndReleaseStagingRepository

