name: Publish Release
on:
  push:
    tags:
      - v3.**.**.**

env:
  GPG_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  GPG_PASSWORD: ${{ secrets.SIGN_PASS }}
  OSSRH_USER: ${{ secrets.OSS_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSS_PASSWORD }}

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # setup Gradle
      - name: Gradle Run Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
          arguments: clean build test



  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # the gpg
      - name: Decode Gpg File
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }}
        env:
          SIMBOT_IS_SNAPSHOT: false
          SIMBOT_RELEASES_ONLY: true

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: write
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2

        # Create gitHub release
      - name: Create Github Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}

  publish-snapshot:
    name: Publish snapshot
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2

      # setup Java
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # the gpg
      - name: Decode gpg file
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle publish snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
          arguments: clean test publishToSonatype closeAndReleaseStagingRepository
        env:
          SIMBOT_IS_SNAPSHOT: true
          SIMBOT_SNAPSHOT_ONLY: true

